'use client';

import React from 'react';
import ProductPageTemplate from '@/components/ProductPageTemplate';
import WhyChooseUs from '@/components/WhyChooseUs';
import { FileText, CreditCard, RefreshCw, CheckCircle } from 'lucide-react';

const NachEcsHeroGraphic = () => {
    return (
        <svg viewBox="0 0 600 500" className="w-full h-full drop-shadow-xl" fill="none" xmlns="http://www.w3.org/2000/svg">
            <circle cx="300" cy="250" r="200" fill="#F3E8FF" />
            
            {/* Center Circle - Processing */}
            <circle cx="300" cy="250" r="80" fill="white" stroke="#6D3078" strokeWidth="4" />
            
            {/* Arrows for Cycle/Automation */}
            <path d="M300 190 A 60 60 0 0 1 352 220" stroke="#F47E4D" strokeWidth="6" strokeLinecap="round" />
            <path d="M352 220 L358 210 M352 220 L342 218" stroke="#F47E4D" strokeWidth="6" strokeLinecap="round" strokeLinejoin="round" />
            
            <path d="M300 310 A 60 60 0 0 1 248 280" stroke="#F47E4D" strokeWidth="6" strokeLinecap="round" />
            <path d="M248 280 L242 290 M248 280 L258 282" stroke="#F47E4D" strokeWidth="6" strokeLinecap="round" strokeLinejoin="round" />

            {/* Icons inside */}
            <rect x="275" y="235" width="50" height="30" rx="4" fill="#6D3078" />
            <line x1="280" y1="245" x2="320" y2="245" stroke="white" strokeWidth="2" />
            <circle cx="315" cy="255" r="3" fill="#F47E4D" />

            {/* Additional floating elements */}
            <circle cx="180" cy="180" r="40" fill="white" stroke="#6D3078" strokeWidth="2" opacity="0.8" />
            <text x="180" y="185" fontSize="12" textAnchor="middle" fill="#6D3078" fontWeight="bold">ECS</text>

            <circle cx="420" cy="180" r="40" fill="white" stroke="#6D3078" strokeWidth="2" opacity="0.8" />
            <text x="420" y="185" fontSize="12" textAnchor="middle" fill="#6D3078" fontWeight="bold">NACH</text>
            
            <circle cx="180" cy="320" r="30" fill="white" stroke="#F47E4D" strokeWidth="2" opacity="0.8" />
             <text x="180" y="325" fontSize="20" textAnchor="middle" fill="#F47E4D" fontWeight="bold">₹</text>

            <circle cx="420" cy="320" r="30" fill="white" stroke="#F47E4D" strokeWidth="2" opacity="0.8" />
            <CheckCircle x="405" y="305" size={30} color="#22c55e" />
        </svg>
    )
}

const NachEcsPage = () => {
    const heroData = {
        title: "NACH / ECS",
        description: "Seamless and automated payment solutions for worry-free repayments.",
        Graphic: NachEcsHeroGraphic
    };

    const infoData = {
        imageSrc: "https://images.unsplash.com/photo-1563013544-824ae1b704d3?ixlib=rb-4.0.3&auto=format&fit=crop&w=1000&q=80", // Generic finance/payment image
        subtitle: "Automated Payments",
        title: "NACH & ECS Mandates",
        intro: "Simplify your EMI payments with National Automated Clearing House (NACH) and Electronic Clearing Service (ECS).",
        description: "NACH and ECS are electronic payment systems that facilitate bulk transfers, making it easier for you to manage recurring payments like EMIs without manual intervention. This ensures timely payments and helps you maintain a good credit history.",
        faqs: [
            {
                question: "What is NACH and ECS?",
                answer: "NACH (National Automated Clearing House) is a centralized system for bulk electronic payments and collections, managed by NPCI, and offers nationwide coverage. ECS (Electronic Clearing Service) is an older system for bulk payments, mainly used regionally for purposes like salary or bill payments."
            },
            {
                question: "How do I set up a NACH/ECS mandate?",
                answer: "To set up a NACH/ECS mandate, you can either fill out the form provided by our NBFC at your nearest branch or authorize its activation online through Net Banking or a debit card, once a request is generated by our team. This authorizes automated debits for your recurring payments or EMIs. After submission, your bank will verify and activate the mandate."
            },
            {
                question: "What happens if my NACH/ECS transaction fails?",
                answer: "If your transaction fails due to insufficient funds or incorrect details, your bank may charge a penalty known as a NACH/ECS return charge. These charges vary by bank and are not refundable."
            },
            {
                question: "Can I cancel or modify my NACH/ECS mandate?",
                answer: "You can cancel or modify your mandate for closed loans or inactive accounts. However, mandates for active loans typically cannot be cancelled until the loan is fully repaid."
            },
            {
                question: "What are the benefits of NACH/ECS?",
                answer: "1. Automated payments save time and effort for both customers and NBFCs. 2. Reduces the risk of missed payments and late fees. 3. Provides secure, paperless, and convenient payment options."
            },
            {
                question: "What should I do if I face issues with my NACH/ECS transactions?",
                answer: "For any issues related to failed transactions, disputes, or mandate-related queries, please contact our customer support team. You may also register your grievance through our dedicated grievance redressal channels for prompt assistance."
            }
        ]
    };

    const documentsData = [
        { title: "Bank Mandate Form", desc: "Physical form available at branches", icon: <FileText className="w-6 h-6" /> },
        { title: "Net Banking / Debit Card", desc: "For e-Mandate authorization", icon: <CreditCard className="w-6 h-6" /> },
    ];

    return (
        <ProductPageTemplate hero={heroData} info={infoData} documents={documentsData} whyChooseUs={<WhyChooseUs />} showApplyButton={false} />
    );
};

export default NachEcsPage;
